# Generated by Django 4.2.13 on 2026-05-21 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('achat', 'Achat'), ('location', 'Location LLD')], max_length=10, verbose_name='Type de dossier')),
                ('status', models.CharField(choices=[('soumis', 'Soumis'), ('en_cours', "En cours d'instruction"), ('valide', 'Validé'), ('refuse', 'Refusé')], default='soumis', max_length=10, verbose_name='Statut')),
                ('motif', models.TextField(blank=True, verbose_name='Motif / Commentaire gestionnaire')),
                ('revenus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Revenus nets/mois (€)')),
                ('situation', models.CharField(blank=True, max_length=50, verbose_name='Situation professionnelle')),
                ('message', models.TextField(blank=True, verbose_name='Message du client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(choices=[('cni', "Pièce d'identité"), ('permis', 'Permis de conduire'), ('revenus', 'Justificatif de revenus'), ('rib', 'RIB'), ('autre', 'Autre')], max_length=15, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to='dossiers/%Y/%m/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
