# Generated by Django 4.2.13 on 2026-05-22 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_svc_assistance_vehicle_svc_assurance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('achat', 'Achat'), ('location', 'Location LLD')], max_length=10, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (€)')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('km_initial', models.PositiveIntegerField(default=0, verbose_name='Km initial')),
                ('km_actuel', models.PositiveIntegerField(default=0, verbose_name='Km actuel')),
                ('signature_nom', models.CharField(blank=True, max_length=120, verbose_name='Nom signataire')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('resilie', 'Résilié')], default='actif', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrat', to='dossiers.dossier', verbose_name='Dossier')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-created_at'],
            },
        ),
    ]
