# Generated by Django 4.2.13 on 2026-05-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_add_contrat_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
    ]
