# Generated by Django 4.2.13 on 2026-06-08 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossiers', '0007_sav_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAVMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sav_messages', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sav_messages', to='dossiers.savticket', verbose_name='Ticket SAV')),
            ],
            options={
                'verbose_name': 'Message SAV',
                'verbose_name_plural': 'Messages SAV',
                'ordering': ['created_at'],
            },
        ),
    ]
