# Generated by Django 4.2.13 on 2026-05-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Marque')),
                ('model', models.CharField(max_length=80, verbose_name='Modèle')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('km', models.PositiveIntegerField(default=0, verbose_name='Kilométrage')),
                ('fuel', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Hybride', 'Hybride'), ('Électrique', 'Électrique')], max_length=20, verbose_name='Carburant')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Couleur')),
                ('doors', models.PositiveSmallIntegerField(default=5, verbose_name='Portes')),
                ('type', models.CharField(choices=[('achat', 'Achat'), ('location', 'Location Longue Durée')], max_length=10, verbose_name='Mode')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('vendu', 'Vendu / Loué')], default='disponible', max_length=15, verbose_name='Statut')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix achat (€)')),
                ('monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Loyer mensuel (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-created_at'],
            },
        ),
    ]
