# Generated by Django 4.2.13 on 2026-05-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='svc_assistance',
            field=models.BooleanField(default=True, verbose_name='Assistance dépannage incluse'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='svc_assurance',
            field=models.BooleanField(default=True, verbose_name='Assurance tous risques incluse'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='svc_ct',
            field=models.BooleanField(default=True, verbose_name='Contrôle technique inclus'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='svc_entretien',
            field=models.BooleanField(default=True, verbose_name='Entretien & SAV inclus'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='svc_options',
            field=models.JSONField(blank=True, default=list, verbose_name='Options supplémentaires'),
        ),
    ]
